### ISSUE TITLE
TypeError: 'CommandCursor' object is unsubscriptabl

### ISSUE THREAD

**Issue by ibobak** [AlchemyAPI/alchemyapi-recipes-twitter#5]
launched the command 
python recipe.py "Tesla Model S" 100
and received this error.  MongoDB database is filled in fine - I see 98 tweets, everything is fine.

Traceback (most recent call last):
  File "recipe.py", line 340, in <module>
    main(sys.argv[1], int(sys.argv[2]))
  File "recipe.py", line 43, in main
    print_results()
  File "recipe.py", line 303, in print_results
    avg_pos_score = mean_results['result'][2]['avgScore'] 
TypeError: 'CommandCursor' object is unsubscriptable

**Comment by ibobak** [comment]
and there is a bug on your page
http://www.alchemyapi.com/developers/getting-started-guide/twitter-sentiment-analysis

instead of "analyze.py" it should be "recipe.py"

**Comment by christieewen** [comment]
+1

**Comment by randywreed** [comment]
I know this is old, but in case others show up here looking for answers. While I did not get the same error. I did get an error on this line ("IndexError: list index out of range" -- the error is probably different because I am running 2.7) However I suspect the cause is the same.

This is an error in the code. Line 303 should be 
`avg_pos_score=mean_results['result'][0]['avgScore']`

change the 2 to 0 and the code should run properly.
